; ============================================================================
; Solscan Hotkey Script
; ============================================================================
; Description: Click side mouse button over a Solana address to open Solscan
; Author: Generated by Claude Code
; Version: 1.0
; ============================================================================

#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%
SendMode Input
SetBatchLines -1
CoordMode, Mouse, Screen

; Configuration
global NOTIFICATION_DURATION := 2000  ; milliseconds
global SELECTION_DELAY := 100         ; delay after selection before copy

; ============================================================================
; MAIN HOTKEY: XButton1 (Side Mouse Button - typically "Back" button)
; ============================================================================
; Change to XButton2 if you prefer the "Forward" button
; ============================================================================

XButton1::
    HandleSolscanLookup()
return

; ============================================================================
; Core Function: Capture text and open Solscan
; ============================================================================

HandleSolscanLookup() {
    ; Save original clipboard
    ClipSaved := ClipboardAll
    Clipboard := ""

    ; Try to capture text under cursor
    address := CaptureTextUnderCursor()

    ; Restore clipboard immediately
    Clipboard := ClipSaved
    ClipSaved := ""

    ; Validate and process
    if (address != "") {
        if (IsValidSolanaAddress(address)) {
            OpenSolscan(address)
            ShowNotification("Opening Solscan...", address)
        } else {
            ShowNotification("Not a valid Solana address", address)
        }
    } else {
        ShowNotification("No text captured", "Hover over an address and try again")
    }
}

; ============================================================================
; Text Capture Logic
; ============================================================================

CaptureTextUnderCursor() {
    ; Strategy 1: Check if text is already selected
    Send, ^c
    ClipWait, 0.2
    if (Clipboard != "" && StrLen(Clipboard) > 0) {
        return Trim(Clipboard)
    }

    ; Strategy 2: Smart word selection
    ; Double-click to select word under cursor
    Click
    Sleep, 50
    Click
    Sleep, %SELECTION_DELAY%

    ; Copy selected text
    Send, ^c
    ClipWait, 0.3
    if (Clipboard != "" && StrLen(Clipboard) > 0) {
        captured := Trim(Clipboard)
        return captured
    }

    ; Strategy 3: Select entire line (fallback)
    Send, {Home}
    Send, +{End}
    Sleep, %SELECTION_DELAY%
    Send, ^c
    ClipWait, 0.3
    if (Clipboard != "" && StrLen(Clipboard) > 0) {
        ; Try to extract address from line
        return ExtractAddressFromText(Clipboard)
    }

    return ""
}

; ============================================================================
; Validation: Solana Address Pattern
; ============================================================================

IsValidSolanaAddress(text) {
    ; Remove whitespace and quotes
    text := Trim(text)
    text := StrReplace(text, "`r", "")
    text := StrReplace(text, "`n", "")
    text := StrReplace(text, " ", "")
    text := StrReplace(text, """", "")
    text := StrReplace(text, "'", "")

    ; Solana addresses are base58 encoded, 32-44 characters
    length := StrLen(text)
    if (length < 32 || length > 44) {
        return false
    }

    ; Check if all characters are valid base58 (excludes 0, O, I, l)
    Loop, Parse, text
    {
        char := A_LoopField
        ; Base58 alphabet: 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz
        if !RegExMatch(char, "[1-9A-HJ-NP-Za-km-z]") {
            return false
        }
    }

    return true
}

; ============================================================================
; Helper: Extract address from longer text
; ============================================================================

ExtractAddressFromText(text) {
    ; Try to find a base58 string of correct length
    if RegExMatch(text, "[1-9A-HJ-NP-Za-km-z]{32,44}", match) {
        return match
    }
    return ""
}

; ============================================================================
; Action: Open Solscan in Browser
; ============================================================================

OpenSolscan(address) {
    url := "https://solscan.io/account/" . address
    Run, %url%
}

; ============================================================================
; UI Feedback: Toast Notification
; ============================================================================

ShowNotification(title, message) {
    ToolTip, % title . "`n" . message
    SetTimer, RemoveToolTip, %NOTIFICATION_DURATION%
}

RemoveToolTip:
    SetTimer, RemoveToolTip, Off
    ToolTip
return

; ============================================================================
; Optional: XButton2 as alternative trigger
; ============================================================================
; Uncomment below to enable the "Forward" button as well:
; XButton2::
;     HandleSolscanLookup()
; return

; ============================================================================
; Exit Hotkey: Ctrl+Alt+Q to quit script
; ============================================================================

^!q::
    MsgBox, 4, Exit Solscan Hotkey, Are you sure you want to exit?
    IfMsgBox Yes
        ExitApp
return

; ============================================================================
; Tray Menu Customization
; ============================================================================

Menu, Tray, Tip, Solscan Hotkey Active (XButton1)
Menu, Tray, NoStandard
Menu, Tray, Add, Reload Script, ReloadScript
Menu, Tray, Add, Exit, ExitScript
return

ReloadScript:
    Reload
return

ExitScript:
    ExitApp
return
