; ============================================================================
; Solscan Hotkey Script
; ============================================================================
; Description: Click side mouse button over a Solana address to open Solscan
; Author: Generated by Claude Code
; Version: 2.0 (AutoHotkey v2)
; ============================================================================

#Requires AutoHotkey v2.0
#SingleInstance Force
SetWorkingDir A_ScriptDir
SendMode "Input"
CoordMode "Mouse", "Screen"

; Configuration
NOTIFICATION_DURATION := 2000  ; milliseconds
SELECTION_DELAY := 100         ; delay after selection before copy

; ============================================================================
; MAIN HOTKEY: XButton2 (Side Mouse Button - typically "Forward" button)
; ============================================================================
; Change to XButton1 if you prefer the "Back" button
; ============================================================================

XButton2::HandleSolscanLookup()

; ============================================================================
; Core Function: Capture text and open Solscan
; ============================================================================

HandleSolscanLookup() {
    ; Save original clipboard
    ClipSaved := ClipboardAll()
    A_Clipboard := ""

    ; Try to capture text under cursor
    capturedText := CaptureTextUnderCursor()

    ; Restore clipboard immediately
    A_Clipboard := ClipSaved
    ClipSaved := ""

    ; Process captured text
    if (capturedText != "") {
        ; First, try to extract an address from the text (handles URLs and mixed content)
        address := ExtractAddressFromText(capturedText)

        ; If extraction found nothing, check if the whole text is a valid address
        if (address == "" && IsValidSolanaAddress(capturedText)) {
            address := capturedText
        }

        ; Validate and open
        if (address != "" && IsValidSolanaAddress(address)) {
            OpenSolscan(address)
            ShowNotification("Opening Solscan...", address)
        } else {
            ShowNotification("Not a valid Solana address", capturedText)
        }
    } else {
        ShowNotification("No text captured", "Hover over an address and try again")
    }
}

; ============================================================================
; Text Capture Logic
; ============================================================================

CaptureTextUnderCursor() {
    ; Strategy 1: Check if text is already selected
    Send "^c"
    if ClipWait(0.2) {
        if (A_Clipboard != "" && StrLen(A_Clipboard) > 0) {
            return Trim(A_Clipboard)
        }
    }

    ; Strategy 2: Double-click to select word under cursor
    Click
    Sleep 50
    Click
    Sleep SELECTION_DELAY

    ; Copy selected text
    Send "^c"
    if ClipWait(0.3) {
        if (A_Clipboard != "" && StrLen(A_Clipboard) > 0) {
            captured := Trim(A_Clipboard)
            return captured
        }
    }

    ; Strategy 3: Select entire line (fallback)
    Send "{Home}"
    Send "+{End}"
    Sleep SELECTION_DELAY
    Send "^c"
    if ClipWait(0.3) {
        if (A_Clipboard != "" && StrLen(A_Clipboard) > 0) {
            return A_Clipboard
        }
    }

    return ""
}

; ============================================================================
; Validation: Solana Address Pattern
; ============================================================================

IsValidSolanaAddress(text) {
    ; Remove whitespace and quotes
    text := Trim(text)
    text := StrReplace(text, "`r", "")
    text := StrReplace(text, "`n", "")
    text := StrReplace(text, " ", "")
    text := StrReplace(text, '"', "")
    text := StrReplace(text, "'", "")

    ; Solana addresses are base58 encoded, 32-44 characters
    length := StrLen(text)
    if (length < 32 || length > 44) {
        return false
    }

    ; Check if all characters are valid base58 (excludes 0, O, I, l)
    Loop Parse, text
    {
        char := A_LoopField
        ; Base58 alphabet: 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz
        if !RegExMatch(char, "[1-9A-HJ-NP-Za-km-z]") {
            return false
        }
    }

    return true
}

; ============================================================================
; Helper: Extract address from longer text
; ============================================================================

ExtractAddressFromText(text) {
    ; Try to find a base58 string of correct length
    if RegExMatch(text, "[1-9A-HJ-NP-Za-km-z]{32,44}", &match) {
        return match[0]
    }
    return ""
}

; ============================================================================
; Action: Open Solscan in Browser
; ============================================================================

OpenSolscan(address) {
    ; Custom Solscan URL with your preferred filters
    url := "https://solscan.io/account/" . address . "?activity_type=ACTIVITY_SPL_TRANSFER&exclude_amount_zero=true&remove_spam=true&value=100&value=&token_address=So11111111111111111111111111111111111111111&page_size=10#transfers"
    Run url
}

; ============================================================================
; UI Feedback: Toast Notification
; ============================================================================

ShowNotification(title, message) {
    ToolTip title . "`n" . message
    SetTimer () => ToolTip(), -NOTIFICATION_DURATION
}

; ============================================================================
; Optional: XButton1 as alternative trigger
; ============================================================================
; Uncomment below to enable the "Back" button as well:
; XButton1::HandleSolscanLookup()

; ============================================================================
; Exit Hotkey: Ctrl+Alt+Q to quit script
; ============================================================================

^!q:: {
    result := MsgBox("Are you sure you want to exit?", "Exit Solscan Hotkey", "YesNo")
    if (result = "Yes") {
        ExitApp
    }
}

; ============================================================================
; Tray Menu Customization
; ============================================================================

A_TrayMenu.Delete()
A_TrayMenu.Add("Reload Script", (*) => Reload())
A_TrayMenu.Add("Exit", (*) => ExitApp())
A_IconTip := "Solscan Hotkey Active (XButton2)"